# Generated by Django 6.0.3 on 2026-03-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['-id']},
        ),
    ]
